spring.application.name=planeo_back
--spring.profiles.active=dev
server.port=8082

# Configuration BDD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#Servlet
server.servlet.contextPath=/api