spring.datasource.url=jdbc:mysql://planeo-back-db:3306/planeo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

spring.kafka.bootstrap-servers=kafka:9092
